version: "3.8"
networks:
  ingress:
    driver: bridge
services:
  mongo-db:
    container_name: 'bom-mongo-db'
    image: 'mongo:latest'
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - '27100:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
      - MONGO_INITDB_DATA_PATH=/data/db
    restart: on-failure
    networks:
      - ingress
  postgres-db:
    image: postgres:15.2-alpine
    container_name: pg_container
    # restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    # restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks:
      - ingress
    depends_on:
      - postgres-db