version: "3.8"
networks:
  ingress:
    driver: bridge
services:
  mongo-db:
    container_name: 'bom-mongo-db'
    image: 'mongo:latest'
    volumes:
      - ./mongo-db/dev/mongo:/data/db
    ports:
      - '27100:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
      - MONGO_INITDB_DATA_PATH=/data/db
    restart: on-failure
    networks:
      - ingress
  postgres-db:
    image: postgres:15.2-alpine
    container_name: bom-postgres-db
    # restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-db:/var/lib/postgresql/data